POST http://localhost:8080/api/chat/simple
Content-Type: application/json

{
  "message": "안녕하세요!"
}

### 2. 대화 히스토리를 유지하는 채팅
POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "message": "Spring AI에 대해 설명해줘",
  "conversationId": null
}

### 3. 같은 대화 이어서 하기
POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "message": "방금 설명한 내용을 요약해줘",
  "conversationId": "이전-응답의-conversationId"
}

### 4. 스트리밍 채팅
POST http://localhost:8080/api/chat/stream
Content-Type: application/json

{
  "message": "긴 이야기를 들려줘"
}

### Postman/Insomnia 테스트

POST http://localhost:8080/api/chat
Content-Type: application/json

{
  "message": "Spring Boot와 Spring AI의 차이점은?",
  "conversationId": null
}

###
GET http://localhost:8080/api/v1/tools/weather

###
GET http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst?ServiceKey=VGm26lrei89KuhKKG%2BrhvSRsQ1n1kHUEnt6EjxfUzSNJUb4TAH4miOEl8JCix5p1pp8mm6zSrTWolibNkT7I0w%3D%3D&pageNo=1&numOfRows=1000&dataType=JSON&base_date=20250611&base_time=0600&nx=55&ny=127

###
GET https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst?ServiceKey=VGm26lrei89KuhKKG+rhvSRsQ1n1kHUEnt6EjxfUzSNJUb4TAH4miOEl8JCix5p1pp8mm6zSrTWolibNkT7I0w==
    &pageNo=1&numOfRows=1000&dataType=JSON&base_date=20250611&base_time=0600&nx=55&ny=127
####
GET https://apihub.kma.go.kr/api/typ01/url/kma_sfctm2.php?stn=108&authKey=FAVWlSB7Qa6FVpUgezGuHw

###
Asdfg1234!@#$
FAVWlSB7Qa6FVpUgezGuHw


###
POST http://localhost:8080/api/mcp/chat/simple
Content-Type: application/json

{
  "message": "오늘 서울 날씨 어때?"
}